function radius = importPtsRadius(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RADIUS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a string array.
%
%  RADIUS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  radius = importfile("Z:\Tumor\Bachelor thesis\pts\pts\4_radius_.pts", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Jun-2020 18:28:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "BEGIN_LIST";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "BEGIN_LIST", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "BEGIN_LIST", "EmptyFieldRule", "auto");

% Import the data
radius = readmatrix(filename, opts);

end